version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/dump:/docker-entrypoint-initdb.d
    networks:
      - taskmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: taskmanager-postgres-data

networks:
  taskmanager-network:
    name: taskmanager-network
    driver: bridge